# Github action

name: Build, Run and move Files to GCP
'on':
  schedule:
  # Runs "At 22:00 on Saturday." (see https://crontab.guru)
    - cron: '0 22 * * 6'

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'
    
  steps:
    - id: 'Actions Checkout'
      uses: actions/checkout@master
    - id: 'Install Dependencies'
      run: npm install
    - id: 'Build'
      run: npm run update_stats 
    - id: 'Auth'
      uses: 'google-github-actions/auth@v0'
      with:
        service_account: 'tgfparkrun-github@tgfparkrun.iam.gserviceaccount.com'
    - id: 'Upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: './_completedRosters/'
        destination: 'tgfparkrun'update
      - id: 'Upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './_runResults/'
          destination: 'tgfparkrun'