# Github action

name: Build, Run and move Files to GCP
'on':
  workflow_dispatch:
  schedule:
    # Runs "At 22:00 on Saturday." (see https://crontab.guru)
    - cron: '0 22 * * 6'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run update_stats

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GCP_SECRET }}'

    - name: Upload Folder
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: '_completedRosters'
        destination: tgfparkrun

    - name: Upload Folder2
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: '_runResults'
        destination: tgfparkrun
