# Github action

name: Run update stats and move to BigQuery
'on':
  workflow_dispatch:
  #schedule:
  # Runs "At 22:00 on Saturday." (see https://crontab.guru)
  # - cron: '0 22 * * 6'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Process Latest Results
        env:
          UNAME: '${{ secrets.UNAME }}'
          PWORD: '${{ secrets.PWORD }}'
          EVENTID: '${{ secrets.EVENTID }}'
          JUNAME: '${{ secrets.JUNAME }}'
          JPWORD: '${{ secrets.JPWORD }}'
          JEVENTID: '${{ secrets.JEVENTID }}'
          GA_CREDS: '${{ secrets.GA_CREDS }}'
        run: npm run getLatest

      - name: Send to BigQuery
        env:
          UNAME: '${{ secrets.UNAME }}'
          PWORD: '${{ secrets.PWORD }}'
          EVENTID: '${{ secrets.EVENTID }}'
          JUNAME: '${{ secrets.JUNAME }}'
          JPWORD: '${{ secrets.JPWORD }}'
          JEVENTID: '${{ secrets.JEVENTID }}'
          GA_CREDS: '${{ secrets.GA_CREDS }}'
        run: npm run uploadLatest
